config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors, controllers: {
    registrations: 'instructors/registrations'
  }, path_names: {
    edit: 'account/edit'
  }

  devise_for :students, skip: [:registrations]

  devise_scope :instructor do
    post 'instructors/guest_sign_in', to: 'instructors/sessions#guest_sign_in'
  end

  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#guest_sign_in'

    get 'instructors/students/new', to: 'students/registrations#new', as: :new_student_registration
    post 'instructors/students', to: 'students/registrations#create', as: :student_registration
    get 'students/account/edit', to: 'students/registrations#edit', as: :edit_student_registration
    patch 'students/account', to: 'students/registrations#update', as: :update_student_registration
    put 'students/account', to: 'students/registrations#update'
  end

  get 'instructors/profile', to: 'instructors#profile', as: :instructor_profile
  get 'instructors/profile/edit', to: 'instructors#profile_edit', as: :instructor_profile_edit
  patch 'instructors/profile/edit', to: 'instructors#profile_update'

  get 'students/profile', to: 'students/profiles#profile', as: :student_profile
  get 'students/profile/edit', to: 'students/profiles#profile_edit', as: :student_profile_edit
  patch 'students/profile/edit', to: 'students/profiles#profile_update'

  namespace :instructors do
    resources :students, path: 'my-students', only: [:index, :show, :edit, :update, :destroy]
  end

  resources :lessons do
    collection do
      get 'student_index', to: 'lessons#student_index'
    end
  end

  namespace :instructors do
    resources :lesson_notes
  end

  namespace :students do
    resources :lesson_notes, only: [:index, :show, :edit, :update]
  end

  root "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/student.rb
class Student < ApplicationRecord
  mount_uploader :icon_image, IconImageUploader
  belongs_to :instructor
  has_many :lessons, dependent: :destroy
  has_many :lesson_notes, dependent: :nullify
  before_create :set_enrollment_date

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :student_name, presence: true, length: { maximum: 20 }
  validates :course, length: { maximum: 50 }

  def self.guest
    guest_instructor = Instructor.guest
    find_or_create_by!(email: 'guest_student@example.com') do |student|
      student.password = SecureRandom.urlsafe_base64
      student.student_name = 'ゲスト 生徒'
      student.instructor = guest_instructor
    end
  end

  def guest_user?
    email == 'guest_student@example.com'
  end

  private

  def set_enrollment_date
    self.enrollment_date = Date.today
  end
end

app/controllers/instructors/students_controller.rb
class Instructors::StudentsController < ApplicationController
  before_action :authenticate_instructor!, only: %i(index show edit update destroy)
  before_action :set_student, only: %i(show edit update destroy)

  def index
    @students = current_instructor.students
  end

  def show
    @lessons = @student.lessons.
      where('start_time >= ?', Time.current.beginning_of_day).
      order(start_time: :asc)
    @lesson_notes = @student.lesson_notes.order(start_time: :desc)
  end

  def edit
  end

  def update
    if @student.update(student_params_for_instructor)
      redirect_to instructors_student_path(@student), notice: 'プロフィールが更新されました'
    else
      render 'edit'
    end
  end

  def destroy
    if @student.destroy
      redirect_to instructors_students_path, notice: '生徒が削除されました'
    else
      redirect_to instructors_students_path, alert: '生徒の削除に失敗しました'
    end
  end

  private

  def set_student
    @student = Student.find_by(id: params[:id])

    if @student.nil?
      redirect_to instructors_students_path, alert: '指定されたIDの生徒は存在しません。'
    elsif @student.instructor_id != current_instructor.id
      redirect_to instructors_students_path, alert: '指定されたIDの生徒にはアクセスできません。'
    end
  end

  def student_params_for_instructor
    params.require(:student).permit(:student_name, :email, :course, :enrollment_date)
  end
end

app/controllers/students/lesson_notes_controller.rb
class Students::LessonNotesController < ApplicationController
  before_action :authenticate_student!
  before_action :set_lesson_note, only: [:show, :edit, :update]

  def index
    @lesson_notes = LessonNote.where(student_id: current_student.id).order(start_time: :desc)
  end

  def show
    @embed_url = generate_embed_url(@lesson_note.video_material)
  end

  def edit
  end

  def update
    if @lesson_note.update(lesson_note_params)
      redirect_to students_lesson_note_path(@lesson_note), notice: 'メモが更新されました。'
    else
      render :edit
    end
  end

  private

  def set_lesson_note
    @lesson_note = LessonNote.find_by(id: params[:id])

    if @lesson_note.nil?
      redirect_to students_lesson_notes_path, alert: '指定されたレッスンノートは存在しません。'
    elsif @lesson_note.student_id != current_student.id
      redirect_to students_lesson_notes_path, alert: '指定されたレッスンノートにはアクセスできません。'
    end
  end

  def generate_embed_url(material)
    return nil if material.blank?

    if material.include?("youtube.com")
      begin
        youtube_id = material.split("v=").last.split("&").first
      rescue NoMethodError, IndexError
        nil
      end
      return "https://www.youtube.com/embed/#{youtube_id}" if youtube_id
    elsif material.include?("youtu.be")
      youtube_id = material.split("/").last
      return "https://www.youtube.com/embed/#{youtube_id}" if youtube_id.present?
    end

    nil
  end

  def lesson_note_params
    params.require(:lesson_note).permit(:student_memo)
  end
end

app/controllers/students/profiles_controller.rb
class Students::ProfilesController < ApplicationController
  before_action :authenticate_student!, only: %i(profile profile_edit profile_update)
  before_action :ensure_normal_user, only: %i(profile_edit profile_update)

  def profile
    @student = current_student
  end

  def profile_edit
    @student = current_student
  end

  def profile_update
    @student = current_student
    if @student.update(profile_params)
      redirect_to students_profile_path, notice: 'プロフィールが更新されました'
    else
      render 'profile_edit'
    end
  end

  private

  def profile_params
    params.require(:student).permit(:icon_image)
  end

  def ensure_normal_user
    if current_student.guest_user?
      flash[:alert] = 'ゲストユーザーは編集できません。'
      redirect_to student_profile_path
    end
  end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  prepend_before_action :authenticate_instructor!, only: [:new, :create]
  before_action :ensure_normal_user, only: :update

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.instructor_id = current_instructor.id

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :"students.signed_up"
        redirect_to root_path
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        redirect_to root_path
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  def authenticate_instructor!
    if student_signed_in?
      redirect_to root_path, alert: '生徒アカウントでは生徒登録ページにアクセスできません。'
    elsif !instructor_signed_in?
      redirect_to new_instructor_session_path, alert: '生徒登録するには講師アカウントでログインしてください。'
    end
  end

  def ensure_normal_user
    if resource.guest_user?
      flash[:alert] = 'ゲストユーザーは編集できません。'
      redirect_to edit_student_registration_path
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    student = Student.guest
    sign_in student
    redirect_to root_path, notice: 'ゲスト生徒ユーザーとしてログインしました。'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<h1>生徒情報編集</h1>

<%= form_for @student do |f| %>
  <%= render 'shared/error_messages', object: @student %>

  <div class="field">
    <%= f.label :student_name %>
    <%= f.text_field :student_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :course %>
    <%= f.text_field :course %>
  </div>

  <div class="field">
    <%= f.label :enrollment_date %>
    <%= f.date_select :enrollment_date %>
  </div>

  <div class="actions">
    <%= f.submit "更新" %>
  </div>
<% end %>

<%= link_to '戻る', students_path %>

app/views/students/index.html.erb
<h1>生徒一覧</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>アイコン画像</th>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>コース</th>
      <th>入会日</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td>
          <% if student.icon_image.present? %>
            <%= image_tag student.icon_image.url, size: "100x100" %>
          <% else %>
            <%= image_tag 'default_icon.png', alt: 'ユーザーアイコン', size: "100x100" %>
          <% end %>
        </td>
        <td><%= student.student_name %></td>
        <td><%= student.email %></td>
        <td><%= student.course %></td>
        <td><%= student.enrollment_date %></td>
        <td><%= link_to '詳細', student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'ホームに戻る', root_path %></p>

app/views/students/profile.html.erb
<h1>プロフィール</h1>
<h3>アイコン画像</h3>
  <% if @student.icon_image.present? %>
    <%= image_tag @student.icon_image.url, size: "100x100" %>
  <% else %>
    <%= image_tag '/assets/default_icon.png', alt: 'ユーザーアイコン', size: "100x100" %>
  <% end %>
<h3>名前</h3>
<%= @student.student_name %>
<h3>メールアドレス</h3>
<%= @student.email %>
<h3>コース</h3>
<%= @student.course %>

<p><%= link_to 'プロフィール編集', student_profile_edit_path %></p>

app/views/students/show.html.erb
<h1>生徒詳細</h1>
<p>
  <% if @student.icon_image.present? %>
    <%= image_tag @student.icon_image.url, size: "100x100" %>
  <% else %>
    <%= image_tag '/assets/default_icon.png', alt: 'ユーザーアイコン', size: "100x100" %>
  <% end %>
</p>
<p><strong>名前:</strong> <%= @student.student_name %> さん</p>
<p><strong>ID:</strong> <%= @student.id %></p>
<p><strong>メールアドレス:</strong> <%= @student.email %></p>
<p><strong>コース:</strong> <%= @student.course %></p>
<p><strong>入会日:</strong> <%= @student.enrollment_date %></p>
<%= link_to '編集', edit_student_path(@student) %>
<%= link_to '削除', student_path(@student), data: { turbo: "true", turbo_method: :delete, turbo_confirm: '本当に削除しますか？' } %>

<%= link_to '一覧に戻る', students_path %>