config/routes.rb
Rails.application.routes.draw do
  devise_for :instructors, controllers: {
    registrations: 'instructors/registrations'
  }, path_names: {
    edit: 'account/edit'
  }

  devise_for :students, skip: [:registrations]

  devise_scope :instructor do
    post 'instructors/guest_sign_in', to: 'instructors/sessions#guest_sign_in'
  end

  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#guest_sign_in'

    get 'instructors/students/new', to: 'students/registrations#new', as: :new_student_registration
    post 'instructors/students', to: 'students/registrations#create', as: :student_registration
    get 'students/account/edit', to: 'students/registrations#edit', as: :edit_student_registration
    patch 'students/account', to: 'students/registrations#update', as: :update_student_registration
    put 'students/account', to: 'students/registrations#update'
  end

  get 'instructors/profile', to: 'instructors#profile', as: :instructor_profile
  get 'instructors/profile/edit', to: 'instructors#profile_edit', as: :instructor_profile_edit
  patch 'instructors/profile/edit', to: 'instructors#profile_update'

  get 'students/profile', to: 'students/profiles#profile', as: :student_profile
  get 'students/profile/edit', to: 'students/profiles#profile_edit', as: :student_profile_edit
  patch 'students/profile/edit', to: 'students/profiles#profile_update'

  namespace :instructors do
    resources :students, path: 'my-students', only: [:index, :show, :edit, :update, :destroy]
  end

  resources :lessons do
    collection do
      get 'student_index', to: 'lessons#student_index'
    end
  end

  namespace :instructors do
    resources :lesson_notes
  end

  namespace :students do
    resources :lesson_notes, only: [:index, :show, :edit, :update]
  end

  root "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="text-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag 'logo.svg', alt: 'ロゴ', width: '150', height: 'auto' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav ms-auto text-end">
        <% if instructor_signed_in? %>
          <li class="nav-item"><%= link_to 'レッスンカレンダー', lessons_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to '生徒一覧', instructors_students_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'レッスンノート', instructors_lesson_notes_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'プロフィール', instructor_profile_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'アカウント', edit_instructor_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'ログアウト', destroy_instructor_session_path, data: { turbo: "true", turbo_method: :delete }, class: "nav-link" %></li>
        <% elsif student_signed_in? %>
          <li class="nav-item"><%= link_to 'マイレッスン', student_index_lessons_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'レッスンノート', students_lesson_notes_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'プロフィール', student_profile_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'アカウント', edit_student_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'ログアウト', destroy_student_session_path, data: { turbo: "true", turbo_method: :delete }, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to '講師新規登録', new_instructor_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to '講師ログイン', new_instructor_session_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to '生徒ログイン', new_student_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>